//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Memberships = new HashSet<Membership>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int RoleId { get; set; }
        public string Name { get; set; }
        public System.DateTime Dob { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
